### ISSUE TITLE
MiniVM

### ISSUE THREAD

**Issue by filin8804** [philipaconrad/mini-vm#1]
Очень хорошая машина !
Где-бы её применить ?
Спасибо ...

**Comment by philipaconrad** [comment]
The Google Translate result of the above is:

> Very nice car!
> Where to apply it?
> Thanks ...

I am assuming the above user is a bot as a result, and will close this issue.

**Comment by filin8804** [comment]
Спасибо , уважаемый , за программу ...
Проблем нет ...
Спасибо ...
